### ISSUE TITLE
PaperNumberModel _.clone usage

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#214]
What is its purpose?

**Comment by AshrafSharf** [comment]
Have removed clone method from getDigitOffsetPosition of PaperNumber, however clone is required for getOffsetArrayByDigits method. Because for some numbers like 107 which is  3 digit number we need only 2 images (#155) , I clone the imageOffSetPosition array and override this behaviour.
I used clone to leave original array intact
