### ISSUE TITLE
Image Licensing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#48]
@amanda-phet, I see we had new paper artwork, but the digits still look the same as the Snow Day Math sim. Are we planning on keeping these digits (and getting a licensing release), are the numbers part of a font with a compatible license, or are we planning on changing the appearance of the numbers?

**Comment by jonathanolson** [comment]
Also, licensing information for move-cue, edit, split-cue and the level images would be good. I presume they are all from PhET, but adding author information in the license info is always helpful.

**Comment by amanda-phet** [comment]
The digits are custom- they started as a font but were modified before using in Making Tens. 

Move-cue, split-cue, and level images were made by PhET. The edit icon is from font-awesome.

**Comment by jonathanolson** [comment]
Setting the license for the edit icon (SIL open font license, from font-awesome) results in a build error (used license entry information from sherpa):
```
>> Error: Error: Loader plugin did not call the load callback in the build:
>> image:
>>   image!MAKING_TENS/edit.png: Error: unacceptable license entry for MAKING_TENS/edit.png
>> Module loading did not complete for: making-tens-main, MAKING_TENS/making-tens/adding/MakingTensAddingScreen, MAKING_TENS/making-tens/adding/view/M
akingTensAddingScreenView
>>     at Function.build.checkForErrors (c:\Users\jon\phet\git\making-tens\node_modules\requirejs\bin\r.js:30026:19)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
```

Additionally, "modified" to me indicates we still need to include licensing information about the original font.

@samreid, can you provide input on the build error and modified digits?

**Comment by amanda-phet** [comment]
Here is the original font: http://www.dafont.com/crosspatchers-delig.font

**Comment by jonathanolson** [comment]
The license notes for that original font:
```
Thank you for downloading this font!

This font is copyright (c) Jakob Fischer at www.pizzadude.dk,  all rights reserved. Do not distribute without the author's permission.

Use this font for non-commercial use only! If you plan to use it for commercial purposes, contact me before doing so!


For more original fonts take a look at www.pizzadude.dk

Have fun and enjoy!

Jakob Fischer
jakob@pizzadude.dk
www.pizzadude.dk
```

The non-commercial clause would prevent us from delivering the sim with the GPL / CC-by license, and would prevent phet-io usage.

@amanda-phet, how significant were the modifications? The licensing is likely to force us to (a) create custom digits from scratch or (b) use/modify digits with a compatible license. (Sorry if this is the case!)

**Comment by jonathanolson** [comment]
Alternatively, we could ask the original author to release just the digits under a compatible license (due to how we license our sims, we can't just ask for a license that covers PhET-related usage).

**Comment by amanda-phet** [comment]
I am waiting to hear back from @bethstade about how they used the font in Snowday, since I modified it to match that one. When we decided to match the Snowday digits I thought that this was ok as long as it wasn't the exact same font. 

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/7852916/11484220/149db870-976a-11e5-83a1-9860cca8b53c.png)

**Comment by bethstade** [comment]
I would contact my developer Ian directly about how he handled the font question.
Maybe Jon would want to contact him directly?  You can cc me.
iholtum@yahoo.com
Ian Holtum at Silverfern Productions - he does IT and app development for the Denver Museum of Nature and Science.
 
----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Mon, 30 Nov 2015 20:56:55 -0000 (UTC)Subject: Re: [making-tens] Image Licensing (#48)

I am waiting to hear back from @bethstade about how they used the font in Snowday, since I modified it to match that one. When we decided to match the Snowday digits I thought that this was ok as long as it wasn't the exact same font.

&mdash;Reply to this email directly or view it on GitHub.

**Comment by jonathanolson** [comment]
> how he handled the font question

It's under a non-commercial license, so a free educational app like Snow Day probably wouldn't violate copyright. I'm not sure what information he could provide? (Note that the license text actually doesn't explicitly grant anything about derivative works, which is actually separate from just using the font in a non-commercial setting, so I'd be cautious. See https://www.law.cornell.edu/uscode/text/17/106).

The "modified" and "original" still look very similar to each other, and it fits the definition of a derivative work (https://en.wikipedia.org/wiki/Derivative_work) where the original font's author's copyright still applies to the unchanged parts of the digits.

Unless I'm wrong (@samreid, please see what I've said), I'd recommend choosing to either ask the original font author to release the digits under a license that is GPL-compatible (presumably not mentioning Snow Day itself), OR to create new digits from scratch OR derived from a font with a compatible license (like the SIL Open font license).

**Comment by amanda-phet** [comment]
I would be in favor of emailing the original designer but since we had to modify the font anyway it seems like creating new digits (from scratch or derived from a different open font) is the safest way to go.

**Comment by bethstade** [comment]
I agree it makes sense to email the original designer and see if we get a response.

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Mon, 30 Nov 2015 23:24:52 -0000 (UTC)Subject: Re: [making-tens] Image Licensing (#48)

I would be in favor of emailing the original designer but since we had to modify the font anyway it seems like creating new digits (from scratch or derived from a different open font) is the safest way to go.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by amanda-phet** [comment]
@bethstade I *would* be in favor of it except that it seems a lot safer to go a different route. We would not only need him to release the font under a new license, but it would have to include us modifying it. There are plenty of other fonts out there so I think we should at least consider an open one.

**Comment by bethstade** [comment]
sure.
Then we could also shift the numbers up a wee bit to create the"tab" at the bottom for m loving it around.
Whichever way you want to go.

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Mon, 30 Nov 2015 23:48:31 -0000 (UTC)Subject: Re: [making-tens] Image Licensing (#48)

@bethstade I would be in favor of it except that it seems a lot safer to go a different route. We would not only need him to release the font under a new license, but it would have to include us modifying it. There are plenty of other fonts out there so I think we should at least consider an open one.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by samreid** [comment]
For the edit.png--have you considered using it as a font awesome glyph rather than a raster PNG?  It may scale better and also make the licensing problem disappear.

For the fonts, we are in the best position if we restrict our usage to things licensed as public domain or things we create ourselves.  Since Jakob Fischer explicitly put a "non-commercial" restriction in his original license, it seems unlikely he would relicense it as public domain for us to use.  I am not opposed to asking, but how long would it take for our own artists to draw our own numeric fonts for this sim?

**Comment by jonathanolson** [comment]
Probably should have noted from the design meeting today, but we're planning on making modifications based on a font with an SIL Open Font license. I checked the license text, and it supports distributing modified copies.

And for the edit glyph, if it's straight from font-awesome with no modifications (I'll check), I'll replace it with a FontAwesomeNode (adding the SVG path info in if it's not there).

**Comment by jonathanolson** [comment]
Closing, resolved.
