### ISSUE TITLE
Adding screen bug

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#5]
When I try to add 5+6, and drag 1 off of 5 and *immediately* on to 6, this strange bug occurs:

![screen shot 2015-07-01 at 12 11 02 pm](https://cloud.githubusercontent.com/assets/7852916/8461536/aecafbb2-1fea-11e5-8672-3e38c393d5b4.png)
![screen shot 2015-07-01 at 12 11 19 pm 2](https://cloud.githubusercontent.com/assets/7852916/8461539/b3468bf2-1fea-11e5-8d8d-0c4c88f1be46.png)
![screen shot 2015-07-01 at 12 11 23 pm](https://cloud.githubusercontent.com/assets/7852916/8461541/b4e78f10-1fea-11e5-8d4b-9f039eb8592f.png)

**Comment by amanda-phet** [comment]
It seems to be happening with other single-digit numbers as well, but only on the adding screen (not on the explore screen). If I drag a 1 off of a number an immediately on to another (n), it turns the number into 10n+1 instead of n+1.

**Comment by phet-steele** [comment]
Here is a video of the above screenshots:

![mate](https://cloud.githubusercontent.com/assets/5863899/8461760/244e96ea-1fec-11e5-9fe8-131dae7cb46d.gif)

Additionally, it doesn't have to be the case that the user drags a 1 off of a number to the other. It turns out that just dragging the first number in its entirety can cause this bug. This only seems to happen with the first drag as well, and not any subsequent drags.

![mate2](https://cloud.githubusercontent.com/assets/5863899/8461941/6835794a-1fed-11e5-833a-a47bac1cc977.gif)

**Comment by AshrafSharf** [comment]
The issue is fixed now. (The number value had a space which resulted in Text Addition rather than number Addition)

**Comment by amanda-phet** [comment]
This appears to be fixed. Closing.
