### ISSUE TITLE
Testing for when numbers can be added

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#75]
@bethstade or @amanda-phet, has testing been done for when numbers can be added together, or have there been changes from the [original algorithm](https://docs.google.com/document/d/1ZWGrpWBTd1qZjrbgspo5P_g_xP32YCZHoyC4jupY_-8/edit)? I was reviewing the code for this, simplified the logic for the current model on paper, and reduced it to the following (with numbers a and b):
```js
// Don't allow carrying "past" the 100s or 1000s place.
if ( ( a % 1000 ) + ( b % 1000 ) > 1000 || ( a % 100 ) + ( b % 100 ) > 100 ) {
  return false;
}

// Don't allow carrying "past" the 10s place unless one number is a multiple of 10.
return a % 10 === 0 || b % 10 === 0 || ( a % 10 ) + ( b % 10 ) <= 10;
```

I.e. the numbers have to satisfy three conditions:
1. frac(a/1000) + frac(b/1000) <= 1
2. frac(a/100) + frac(b/100) <= 1
3. frac(a/10) + frac(b/10) <= 1 OR at least one number is a multiple of 10.

**This seems different from the original specification**, as certain combinations (23 + 37) can be added together with the current model.

If the current behavior is NOT desired, please reassign to me and I can turn it into a bug issue.

For reference, here is the current code (that simplifies down to the above code), that has the notable expression ```(numberA || numberB < 10)``` that will always evaluate to true:
```js
canAddNumbers: function( numberA, numberB ) {
  numberA = +numberA; // make it an int
  numberB = +numberB;
  var sum = numberA + numberB;
  var modA10 = numberA % 10;
  var modB10 = numberB % 10;

  if ( sum <= 10 ) {
    return true;
  }

  var twoDigits = ((numberA + '').length <= 2 && (numberB + '').length <= 2);

  if ( twoDigits ) {
    // Add with decades. 24 + 50 = 74.
    // Add with decades  20 + 50 = 70
    // cannot cross decades
    // no 24 + 59
    if ( (modA10 === 0 || modB10 === 0) && sum <= 100 ) {
      return true;
    }

    // Add singles to doubles if you don’t go over the decade.(this logic includes the single digit logic above)
    // 23 + 5 = 28
    // 23 +7 = 30
    // cannot cross decades except to meet decade with a single digit.
    // 23 + 7 = 30 okay.
    // but not 23 + 37 (neither A nor B <10)
    // no 23 + 9     (3+9 = 12 not less than = 10)
    // the sum<100  will force user to make 100 when going over 100.

    if ( (numberA || numberB < 10) && ((modA10 + modB10) <= 10) && sum <= 100 ) {
      return true;
    }

    return false;
  }

  var threeDigits = (sum >= 100 && sum <= 1000);
  if ( threeDigits ) {
    return this.validateAdditionForThreeDigits( numberA, numberB );
  }

  var fourDigits = (sum > 1000);
  if ( fourDigits ) {
    if ( numberA === 1000 || numberB === 1000 ) {
      return true;
    }
    var numberC = numberA % 1000;
    var numberD = numberB % 1000;

    // The only way to add over 1000 is to make 1000.
    if ( (numberC + numberD > 1000) ) {
      return false;
    }

    return this.validateAdditionForThreeDigits( numberA, numberB );
  }

  return false;
},

validateAdditionForThreeDigits: function( numberA, numberB ) {
  var numberC = numberA % 100;
  var numberD = numberB % 100;
  //Add with decades. 124 + 150 = 274
  if ( (numberC % 10 === 0 || numberD % 10 === 0) && (numberC + numberD <= 100) ) {
    return true;
  }

  // Add singles to doubles if you don’t go over the decade.   234 + 122 = 156 is ok  but not  97 + 5
  if ( (numberC < 10 || numberD < 10) && (numberC + numberD <= 10) ) {
    return true;
  }

  if ( ((numberA % 10 + numberB % 10) <= 10) && (numberC + numberD <= 100) ) {
    return true;
  }

  return false;

},
```

**Comment by jonathanolson** [comment]
Also to clarify, should the following adds be allowed:
1. 23 + 37 and similar
2. 101 + 102 and similar

**Comment by jonathanolson** [comment]
Also just realized I missed another simplication. Current model is equivalent to:
```js
// Don't allow carrying "past" the 10s, 100s or 1000s place.
return ( a % 1000 ) + ( b % 1000 ) <= 1000 &&
       ( a % 100 ) + ( b % 100 ) <= 100 &&
       ( a % 10 ) + ( b % 10 ) <= 10;
```

So basically:
- **for all x in {10,100,1000} (a mod x) + (b mod x) <= x**

**Comment by bethstade** [comment]
i am looking at this now.

**Comment by bethstade** [comment]
Wow, super elegant solution!
But you are right that the current logic is off - (I will spend some more time with it, thanks for catching that)
I believe the logic at the end of the original Number Logic document is still correct
https://docs.google.com/a/colorado.edu/document/d/1ZWGrpWBTd1qZjrbgspo5P_g_xP32YCZHoyC4jupY_-8/edit?usp=sharing
though not as pretty as yours!
37 + 13 should not add but force you to make the the ten (3+7).
Likewise 670 and 230 should force you to make the 100.
I think that is an important feature to keep, but not QUITE as neat code wise.
So maybe 
for all x in {10,100,1000} (a mod x) + (b mod x) <x, (remove equal)
and then allow all single digits add that add to 10, and decade numbers that add to 100, and century number that add to 1000?

**Comment by jonathanolson** [comment]
> for all x in {10,100,1000} (a mod x) + (b mod x) <x, (remove equal)

Presumably we wouldn't want to remove equality, since for (7+3) with x=10, 7+3 >= 10, the inequality would be false, and we wouldn't be able to add them.

> And then allow all single digits add that add to 10, and decade numbers that add to 100, and century number that add to 1000?

Reading more of the original description, it doesn't seem specified what to do when the two numbers have different numbers of digits (e.g. 4602+10). Additionally, the original description doesn't seem to have a case that would prevent (670+230).

Thus to nail down things exactly, here are some example cases that under the currently-implemented model would be added, and notes about whether they SHOULD be allowed:
1. 13 + 37: no (specified above)
2. 670 + 230: no (specified above)
3. 670 + 229: maybe (like case 2, but also like case 14)
4. 4100 + 1300: presumably no (extends the pattern to bigger numbers)
5. 4187 + 3: presumably yes (completes the 10)
6. 4187 + 13: unknown (completes the 100, but goes past a multiple of 10)
7. 4187 + 12: unknown
8. 4187 + 813: unknown (completes the 1000, but goes past multiples of 10 and 100)
9. 4187 + 801: unknown
10. 4187 + 800: unknown
11. 87 + 13: unknown (completes the 100, but goes past a multiple of 10)
12. 4100 + 13: presumably yes (?)
13. 4100 + 103: unknown
14. 234 + 122: yes? (specified in documentation..?)
15. 1234 + 4321: presumably yes?
16. 4100 + 132: unknown
17. 4000 + 132: presumably yes (no overlapping digits)
18. 4000 + 32: presumably yes (no overlapping digits)
19. 4010 + 101: unknown
20. 4111 + 10: unknown
21. 4191 + 10: no (not allowed with current model, just want to make sure)
22. 4910 + 100: no (not allowed with current model, just want to make sure)
23. 101 + 10: unknown
24. 23 + 67: no (presumably following specified pattern)

@bethstade, would you be available to answer yes/no for all of the above? ("yes" if the addition is allowed, "no" if it is not allowed, and general reasoning for the choices?)

**Comment by jonathanolson** [comment]
Also to clarify how the number logic document seems to indicate how 670 + 230 is acceptable:

> If Sum(A,B) > 100 and <= 1000

Yup

> Then 
> C = double digit of A
> D = double digit of B

C = 70, D = 30

> AND 
> If( C mod 10  == 0 OR  D mod 10  == 0)  
> Add with decades. 124 + 150 = 274.

Satisfies this case, as both (70 mod 10) and (30 mod 10) are both zero, which satisfies the 'if', indicating they can be added (instead of being "bounced").

**Comment by bethstade** [comment]
yes, I will go thru the list.  We originally did't intend to go into the thousands and never fully considered how that affects the adding logic.  I will go thru and find a consistent logic and rational.  Thanks.

**Comment by bethstade** [comment]
Let me try from the start.
I am working on getting a consistent logic throughout now that we are going up to 10,000. 
Here is bit of context. 
In the original iPad app, my rule was simple, if you had to carry at all, it didn't add, except for single digits that add to 10, and decade numbers that add to 100.  so 3 + 7, and 30 + 70.  Simple.  So even 23 + 7, you had to make the ten and add it back to the 20.  
However, working with some teachers and a math specialist, they really felt it was "unnatural," because completing the 30 was an important strategy - you just wouldn't ever break up 23.  However, 23 + 17 was not such a "natural" and automatic sum, in fact, it is one that really trips up the kids, so we DID want the kids to put in the effort here.
Similarly, we didn't want to kids to go over 100 without putting in some effort.  
So we added the rule that single digits could add to double if it completed the decade.
We also wanted to make sure you had to do some work to get over 100, so you can't add 91 +10, which is consistent with "don't add if you need to carry."
***Adding single digits to complete the decade DOES feel natural and is worthwhile.

However, how to scale up this idea is not obvious. (on the iPad we fudged it, didn't try for a consistent strategy, and didn't deal with 1000s at all)


However, what isn't clear is how to scale this up, but let me try.
23 + 7 yes, 23 + 17 no
323 + 7 yes
323 + 77 yes, but 323 + 80 no ( carrying without making 100)
Then 323 + 177, which is the equivalent of 23 +17 no.
But 323 + 677 yes because it makes 1000.
1323 + 677, yes completes  2000
But 1323 + 1677, no because  of 23 +17
But 1323 + 8677 yes because complete 10,000

So I think its makes the rule, if you have to carry at all, don't add, UNLESS:
single digits add to 10.
singles plus doubles add to decade or century.
doubles add to 100 exactly.
single plus triple add makes decade without changing triple digit.
single plus triple add completes century
double plus triple complete century 
triple plus triple makes 1000.

We DO want kids to carry (make tens) otherswise, there is nothing really going on.  But these special cases give a kind of bonus for seeing patterns.

Does this seem consistent? 
Attached answers to your examples in file.
[answers.docx](https://github.com/phetsims/making-tens/files/138722/answers.docx)

**Comment by bethstade** [comment]
one more note,
I really wouldn't mind if we could add 323 and 177, because it is not as essential as 23 +17, but then it is not really consistent, but probably no one would notice - (which I think was my original logic.)

**Comment by bethstade** [comment]
can you send me the lastest dev version so I can look at what have right now in-depth over the weekend? thanks!

**Comment by jonathanolson** [comment]
@amanda-phet and @bethstade, feel free to try out http://www.colorado.edu/physics/phet/dev/html/making-tens/1.0.0-dev.6/making-tens_en.html which has the described algorithm for option 2.

**Comment by bethstade** [comment]
It looks like decade numbers are not adding now.
20 + 30, 40 + 20 etc  are bouncing which should not happen.

otherwise it looks right so far.

**Comment by jonathanolson** [comment]
Those cases would be excluded by the rule given:

> If ( 10 < a < 89) and ( 10 < b < 89) and sum (a + b) = 30,40,50,60,70,80,90

Would a more appropriate rule be that:

a > 10 and b > 10 and a + b < 100 and ( a mod 10 > 0 AND b mod 10 > 0 ) and ( a + b ) mod 10 = 0,

so that it checks whether things are in range (```a > 10 and b > 10 and a + b < 100```), ensures both numbers are not a multiple of 10 (```a mod 10 > 0 AND b mod 10 > 0```), and prevents it if they sum to a multiple of 10 (```( a + b ) mod 10 = 0```)?

**Comment by bethstade** [comment]
Yes, that would be better.
thanks.

----- Original Message -----From: Jonathan Olson <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Wed, 02 Mar 2016 16:46:06 -0000 (UTC)Subject: Re: [making-tens] Testing for when numbers can be added (#75)

Those cases would be excluded by the rule given:

If ( 10 < a < 89) and ( 10 < b < 89) and sum (a + b) = 30,40,50,60,70,80,90

Would a more appropriate rule be that:
a > 10 and b > 10 and a + b < 100 and ( a mod 10 > 0 AND b mod 10 > 0 ) and ( a + b ) mod 10 = 0,
so that it checks whether things are in range (a > 10 and b > 10 and a + b < 100), ensures both numbers are not a multiple of 10 (a mod 10 > 0 AND b mod 10 > 0), and prevents it if they sum to a multiple of 10 (( a + b ) mod 10 = 0)?
&mdash;Reply to this email directly or view it on GitHub.

**Comment by jonathanolson** [comment]
See http://www.colorado.edu/physics/phet/dev/html/making-tens/1.0.0-dev.7/making-tens_en.html updated with the changes.

**Comment by bethstade** [comment]
Looks good now.

**Comment by jonathanolson** [comment]
Merged into master, closing.
